# Use the README file as a reference to customize settings.

User:
  fields:
    default: f_name, l_name, phone, lang, age, description, status, job, email, encrypted_password, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
    form: f_name, l_name, phone, lang, age, description, status, job, email, encrypted_password, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
  relationships: tables
  application: Application
