# Use the README file as a reference to customize settings.

UserTable:
  fields:
    default: user_id, table_id, status
    form: user_id, table_id, status
  relationships: 
  application: Application
